#pragma once

#include "../Displayer.h"

BEG_TL_NAMESPACE

/**
  String stored in a global map.
 */
class GString {
public:
    /**/     GString( const char *str );
    /**/     GString( const Str &str );
    /**/     GString( StrView str );
    /**/     GString() : id( 0 ) {}

    void     display  ( Displayer &dp ) const;
    operator StrView  () const;

    bool     operator==( const GString &that ) const { return id == that.id; }
    bool     operator> ( const GString &that ) const { return id >  that.id; }
    bool     operator< ( const GString &that ) const { return id <  that.id; }

    PI32     id;
};

// generated by StrRefs.py
// beg base string refs
#define STRING_REF_ 0
#define STRING_REF_operator 1
// end base string refs

END_TL_NAMESPACE
