#pragma once

#include "../Displayer.h"

BEG_TL_NAMESPACE

/**
  String stored in a global map.


 */
class StrRef {
public:
    /**/     StrRef( const char *str );
    /**/     StrRef( const Str &str );
    /**/     StrRef( StrView str );
    /**/     StrRef() : id( 0 ) {}

    void     display  ( Displayer &ds ) const;
    operator StrView  () const;

    PI32     id;
};

// generated by StrRefs.py
// beg base string refs
#define STRING_REF_ 0
#define STRING_REF_operator 1
// end base string refs

END_TL_NAMESPACE
